package rules
 
import com.equipecao.model.Programa

//ESTUDO

rule "Cursos de idiomas 1"
	when 
		ProgramaObject: Programa(faixaEtaria >=9 && faixaEtaria <=18)
		               Programa(acomodacao.contains("RE") || acomodacao.contains("CF") || acomodacao.contains("H") || acomodacao.contains("A") || acomodacao.contains("CU"))
		               //Programa(nivel.contains("NA"))
		               Programa(!escolaridade.contains("EM") && !escolaridade.contains("EF"))
		               //Programa(destinos =="NA")
		               Programa(duracao >= 2)
		               Programa(duracao <= 6)
		               Programa(tipoInter=="E")

	then
		ProgramaObject.setCurso("Cursos de idiomas");
		ProgramaObject.setCursoCode("CI");
	end

	rule "Cursos de idiomas 2"
    	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=35)
    		               //Programa(acomodacao.contains("NA"))
    		               Programa(nivel.contains("B"))
    		               //Programa(escolaridade.contains("NA"))
    		               //Programa(destinos =="NA")
    		               Programa(duracao >= 8)
    		               Programa(duracao <= 156)
    		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Cursos de idiomas");
    		ProgramaObject.setCursoCode("CI");
    	end

rule "Oferecer o Programa de Férias 1"
	when
    		ProgramaObject: Programa(faixaEtaria >=9 && faixaEtaria <=18)
    		               Programa(acomodacao.contains("RE") || acomodacao.contains("CA"))
    		               //Programa(nivel.contains("NA"))
    		               Programa(escolaridade.contains("EM"))
    		               //Programa(destinos =="NA")
    		               Programa(duracao >=2 && duracao <=6)
    		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Programa de Férias");
    		ProgramaObject.setCursoCode("PF");
    	end

rule "Oferecer o Programa de Férias 2"
	when
    		ProgramaObject: Programa(faixaEtaria >=9 && faixaEtaria <=18)
                		               Programa(acomodacao.contains("RE") || acomodacao.contains("CA"))
                		               //Programa(nivel.contains("NA"))
                		               Programa(escolaridade.contains("EF"))
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=2 && duracao <=6)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Programa de Férias");
    		ProgramaObject.setCursoCode("PF");

    	end


rule "High School 1"
	when
    		ProgramaObject: Programa(faixaEtaria >=14 && faixaEtaria <=18)
                		               //Programa(acomodacao.contains("NA"))
                		               //Programa(nivel.contains("NA"))
                		               Programa(escolaridade.contains("EM"))
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=2 && duracao <=6)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("High School");
    		ProgramaObject.setCursoCode("HS");
    	end

rule "Estudo 1"
	when
    		ProgramaObject: Programa(faixaEtaria >=9 && faixaEtaria <=18)
                		               //Programa(acomodacao.contains("NA") )
                		               //Programa(nivel.contains("NA"))
                		               //Programa(escolaridade =="NA")
                		               //Programa(destinos =="NA")
                		               Programa(duracao == 0)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Telefone da Experimento");
    		ProgramaObject.setCursoCode("TE");
    	end

rule "Estudo 2"
	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=35)
                		               Programa(acomodacao.contains("RE") || acomodacao.contains("CF") || acomodacao.contains("H"))
                		               Programa(nivel.contains("I"))
                		               //Programa(escolaridade =="NA")
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=8 && duracao <=156)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Programa Universitário e Programa Profissional");
    		ProgramaObject.setCursoCode("PUPP");
    	end

rule "Estudo 3"
	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=35)
                		               Programa(acomodacao.contains("CU"))
                		               Programa(nivel.contains("I"))
                		               //Programa(escolaridade =="NA")
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=8 && duracao <=156)
                		               Programa(tipoInter=="E")
//Se o usuário escolher Campus Universitário, exibir apenas Programa Universitário.
    	then
    		ProgramaObject.setCurso("Programa Universitário");
    		ProgramaObject.setCursoCode("PU");
    	end

rule "Estudo 4"
	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=35)
                		               Programa(acomodacao.contains("RE") || acomodacao.contains("CA") || acomodacao.contains("H"))
                		               Programa(nivel.contains("A"))
                		               //Programa(escolaridade =="NA")
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=8 && duracao <=156)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Formação Profissional ou Programa Universitário");
    		ProgramaObject.setCursoCode("FPPU");
    	end

rule "Estudo 5"
	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=35)
                		               Programa(acomodacao.contains("H"))
                		               Programa(nivel.contains("A"))
                		               //Programa(escolaridade =="NA")
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=8 && duracao <=156)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Formação Profissional");
    		ProgramaObject.setCursoCode("FP");
    	end

rule "Estudo 6"
	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=35)
                		               //Programa(acomodacao.contains("NA"))
                		               Programa(nivel.contains("B"))
                		               // Programa(escolaridade =="NA")
                		               //Programa(destinos =="NA")
                		               Programa(duracao >=8 && duracao <=156)
                		               Programa(tipoInter=="E")

    	then
    		ProgramaObject.setCurso("Curso de Idiomas");
    		ProgramaObject.setCursoCode("CI");
    	end


//TRABALHO

rule "Trabalho + Estudo 1"
	when
    		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=26)
                		               Programa(acomodacao.contains("RE"))
                		               Programa(nivel.contains("B") || nivel.contains("I") || nivel.contains("A") )
                		               Programa(escolaridade.contains("EF"))
                		               Programa(destinos.contains("IRL") || destinos.contains("AUS") || destinos.contains("CAN") || destinos.contains("NZL"))
                		               Programa(duracao >=2 && duracao <=104)
                		               Programa(tipoInter=="TE")

    	then
    		ProgramaObject.setCurso("Trabalho + Estudo");
    		ProgramaObject.setCursoCode("TE");
    	end

 rule "Trabalho voluntário 1"
 	when
     		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=26)
                 		               //Programa(acomodacao.contains("NA"))
                 		               Programa(nivel.contains("I") || nivel.contains("A") )
                 		               Programa(escolaridade.contains("EMC"))
                 		               Programa(destinos.contains("ZA"))
                 		               Programa(duracao >=2 && duracao <=52)
                 		               Programa(tipoInter=="TE")

     	then
     		ProgramaObject.setCurso("Trabalho voluntário");
     		ProgramaObject.setCursoCode("TV");
     	end

 rule "Trabalho voluntário 2"
 	when
     		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=26)
                 		               Programa(acomodacao.contains("CF"))
                 		               Programa(nivel.contains("I")  )
                 		               //Programa(escolaridade =="NA")
                 		               Programa(destinos.contains("EUA"))
                 		               Programa(duracao >=2 && duracao <=104)
                 		               Programa(tipoInter=="TE")
                 		               Programa(gostaCrianca==true)
                 		               Programa(sexo=="F")

     	then
     		ProgramaObject.setCurso("Aupair");
     		ProgramaObject.setCursoCode("AU");
     	end

 rule "Trabalho voluntário 3"
 	when
     		ProgramaObject: Programa(faixaEtaria >=18 && faixaEtaria <=26)
                 		               Programa(acomodacao.contains("CF"))
                 		               Programa(nivel.contains("I"))
                 		               Programa(destinos.contains("AUS"))
                 		               Programa(duracao >=2 && duracao <=104)
                 		               Programa(gostaCrianca==true)
                 		               Programa(sexo=="M")

     	then
     		ProgramaObject.setCurso("Demi pair");
     		ProgramaObject.setCursoCode("DEMI");
     	end